#!/usr/bin/env node
/**
 * coverage-report.mjs
 *
 * Generates Errantry/scenarios/sas/COVERAGE.md by joining:
 *   - Action manifest (~/.sas/actions-manifest.json, populated by `sas refresh`)
 *   - Every scenario YAML under scenarios/sas/**\/*.yaml
 *
 * Each scenario declares which actions it exercises via:
 *   metadata:
 *     exercises:
 *       - <action_name>
 *       - <action_name>
 *
 * The script is name-agnostic — it does NOT bake in any action-specific
 * knowledge. It only reads what the manifest exposes and what scenarios
 * declare. Drift between the CLI surface and test coverage is therefore
 * always visible: any new action shows up as "no scenario yet" until a
 * scenario claims it.
 *
 * Usage:
 *   node Errantry/scripts/coverage-report.mjs
 *   node Errantry/scripts/coverage-report.mjs --out path/to/COVERAGE.md
 *   node Errantry/scripts/coverage-report.mjs --json   # emit raw JSON
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, '..');
const SCENARIOS_DIR = join(REPO_ROOT, 'scenarios', 'sas');
const DEFAULT_MANIFEST = join(homedir(), '.sas', 'actions-manifest.json');
const DEFAULT_OUT = join(SCENARIOS_DIR, 'COVERAGE.md');

function parseFlags(argv) {
  const flags = { out: DEFAULT_OUT, json: false, manifest: DEFAULT_MANIFEST };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') flags.out = argv[++i];
    else if (a === '--json') flags.json = true;
    else if (a === '--manifest') flags.manifest = argv[++i];
  }
  return flags;
}

function loadManifest(path) {
  try {
    const raw = readFileSync(path, 'utf-8');
    const parsed = JSON.parse(raw);
    const actions = Array.isArray(parsed) ? parsed : (parsed.actions ?? []);
    return actions;
  } catch (err) {
    console.error(`ERROR: cannot read action manifest at ${path}`);
    console.error(`Run \`sas refresh\` to populate it. (${err?.message ?? err})`);
    process.exit(1);
  }
}

function findYamlFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) out.push(...findYamlFiles(full));
    else if (st.isFile() && entry.endsWith('.yaml')) out.push(full);
  }
  return out;
}

function loadScenario(file) {
  try {
    const raw = readFileSync(file, 'utf-8');
    const parsed = parseYaml(raw);
    return parsed;
  } catch (err) {
    console.warn(`[coverage] failed to parse ${file}: ${err?.message ?? err}`);
    return null;
  }
}

function buildCoverage(actions, scenarioFiles) {
  // action_name -> [{ scenario, file, goal, exercises }]
  const actionToScenarios = new Map();
  // scenario_name -> { file, goal, exercises }
  const scenariosWithoutMetadata = [];
  const allScenarios = [];

  for (const file of scenarioFiles) {
    const s = loadScenario(file);
    if (!s) continue;
    const rel = relative(REPO_ROOT, file);
    const exercises = Array.isArray(s.metadata?.exercises) ? s.metadata.exercises : [];
    const entry = {
      name: s.name ?? rel,
      file: rel,
      goal: (s.goal ?? '').trim().split('\n')[0],
      exercises,
    };
    allScenarios.push(entry);
    if (exercises.length === 0) {
      scenariosWithoutMetadata.push(entry);
      continue;
    }
    for (const action of exercises) {
      if (!actionToScenarios.has(action)) actionToScenarios.set(action, []);
      actionToScenarios.get(action).push(entry);
    }
  }

  // Bucket actions: those with at least one scenario, those with none.
  const covered = [];
  const uncovered = [];
  for (const a of actions) {
    if (actionToScenarios.has(a.name)) {
      covered.push({ ...a, scenarios: actionToScenarios.get(a.name) });
    } else {
      uncovered.push(a);
    }
  }

  // Scenarios that name an action that ISN'T in the manifest (drift).
  const orphanReferences = [];
  for (const [actionName, scenarios] of actionToScenarios) {
    if (!actions.find((a) => a.name === actionName)) {
      orphanReferences.push({ action: actionName, scenarios });
    }
  }

  return {
    actions,
    allScenarios,
    covered,
    uncovered,
    orphanReferences,
    scenariosWithoutMetadata,
  };
}

function md(coverage) {
  const lines = [];
  const totalActions = coverage.actions.length;
  const coveredCount = coverage.covered.length;
  const pct = totalActions === 0 ? 0 : Math.round((coveredCount / totalActions) * 100);

  lines.push('# SaS CLI — Errantry coverage');
  lines.push('');
  lines.push(`_Generated by \`scripts/coverage-report.mjs\`. Edit scenario \`metadata.exercises\` lists to update; do not hand-edit this file._`);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push(`- **Actions registered**: ${totalActions}`);
  lines.push(`- **Actions covered by ≥1 scenario**: ${coveredCount} (${pct}%)`);
  lines.push(`- **Actions with no scenario yet**: ${coverage.uncovered.length}`);
  lines.push(`- **Total scenarios**: ${coverage.allScenarios.length}`);
  lines.push(`- **Scenarios missing \`metadata.exercises\`**: ${coverage.scenariosWithoutMetadata.length}`);
  if (coverage.orphanReferences.length > 0) {
    lines.push(`- **⚠ Scenarios referencing unknown actions**: ${coverage.orphanReferences.length} (CLI drift; refresh manifest or rename)`);
  }
  lines.push('');

  lines.push('## Covered actions');
  lines.push('');
  if (coverage.covered.length === 0) {
    lines.push('_(none yet)_');
  } else {
    lines.push('| Action | Scenario(s) | Vague prompt(s) |');
    lines.push('| --- | --- | --- |');
    for (const a of coverage.covered) {
      const scenarioLinks = a.scenarios
        .map((s) => `[${s.name}](${s.file})`)
        .join('<br>');
      const goals = a.scenarios
        .map((s) => `"${s.goal.replace(/\|/g, '\\|')}"`)
        .join('<br>');
      lines.push(`| \`${a.name}\` | ${scenarioLinks} | ${goals} |`);
    }
  }
  lines.push('');

  lines.push('## Uncovered actions (no scenario yet)');
  lines.push('');
  if (coverage.uncovered.length === 0) {
    lines.push('_All actions have ≥1 scenario._');
  } else {
    lines.push('Each row is a candidate for a new scenario.');
    lines.push('');
    lines.push('| Action | Description (truncated) | CLI form (if hand-written) |');
    lines.push('| --- | --- | --- |');
    for (const a of coverage.uncovered) {
      const desc = (a.description ?? '').split('\n')[0].slice(0, 110).replace(/\|/g, '\\|');
      const cli = a.cli?.command ? `\`sas ${a.cli.command}\`` : '_(via \`sas run ' + a.name + '\`)_';
      lines.push(`| \`${a.name}\` | ${desc}${desc.length === 110 ? '…' : ''} | ${cli} |`);
    }
  }
  lines.push('');

  if (coverage.orphanReferences.length > 0) {
    lines.push('## ⚠ Drift — scenarios reference unknown actions');
    lines.push('');
    lines.push('A scenario claims to exercise an action the manifest does not know about. Either run `sas refresh` to update the manifest, or rename `metadata.exercises` entries.');
    lines.push('');
    lines.push('| Unknown action | Scenarios |');
    lines.push('| --- | --- |');
    for (const o of coverage.orphanReferences) {
      const scenarioLinks = o.scenarios.map((s) => `[${s.name}](${s.file})`).join('<br>');
      lines.push(`| \`${o.action}\` | ${scenarioLinks} |`);
    }
    lines.push('');
  }

  if (coverage.scenariosWithoutMetadata.length > 0) {
    lines.push('## Scenarios missing `metadata.exercises`');
    lines.push('');
    lines.push('These scenarios run, but their coverage is invisible to this report. Add a `metadata.exercises: [...]` block listing the registered action names they cover.');
    lines.push('');
    for (const s of coverage.scenariosWithoutMetadata) {
      lines.push(`- [${s.name}](${s.file})`);
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

function main() {
  const flags = parseFlags(process.argv.slice(2));
  const actions = loadManifest(flags.manifest);
  const scenarioFiles = findYamlFiles(SCENARIOS_DIR);
  const coverage = buildCoverage(actions, scenarioFiles);

  if (flags.json) {
    process.stdout.write(JSON.stringify(coverage, null, 2) + '\n');
    return;
  }

  const markdown = md(coverage);
  writeFileSync(flags.out, markdown);
  console.log(`[coverage] wrote ${flags.out}`);
  console.log(`[coverage] ${coverage.covered.length}/${coverage.actions.length} actions covered, ${coverage.uncovered.length} uncovered, ${coverage.allScenarios.length} scenarios total`);
}

main();
